services:
  - type: web
    name: detective-conan-api
    runtime: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    healthCheckPath: /api/health
    autoDeploy: true
